// Asset Validation Schemas
const Joi = require('joi');

const createAssetSchema = Joi.object({
  name: Joi.string().required().min(3).max(100),
  assetNumber: Joi.string().optional(),
  assetTag: Joi.string().optional(),
  code: Joi.string().optional(),
  shortDescription: Joi.string().optional().max(500),
  description: Joi.string().optional().max(500),
  category: Joi.string().optional(),
  type: Joi.string().optional(),
  location: Joi.string().optional(),
  propertyLocation: Joi.string().optional(),
  buildingLocation: Joi.string().optional(),
  building: Joi.string().optional(),
  floor: Joi.string().optional(),
  room: Joi.string().optional(),
  serviceArea: Joi.string().optional(),
  serialNumber: Joi.string().optional(),
  serial: Joi.string().optional(),
  manufacturer: Joi.string().optional(),
  modelNumber: Joi.string().optional(),
  model: Joi.string().optional(),
  installationDate: Joi.date().optional(),
  installDate: Joi.date().optional(),
  specs: Joi.object().optional(),
  purchaseDate: Joi.date().optional(),
  purchasePrice: Joi.number().optional().min(0),
  depreciationRate: Joi.number().optional().min(0),
  warranty: Joi.object({
    expires: Joi.date().optional(),
    provider: Joi.string().optional(),
    purchaseDate: Joi.date().optional()
  }).optional(),
  status: Joi.string().optional().valid('active', 'inactive', 'maintenance', 'retired'),
  condition: Joi.string().optional().valid('excellent', 'good', 'fair', 'poor'),
  images: Joi.array().items(Joi.string()).optional(),
  imageUrl: Joi.string().optional(),
  imageUrls: Joi.array().items(Joi.string()).optional(),
  qrCode: Joi.string().optional(),
  notes: Joi.string().optional(),
  maintenanceHistory: Joi.array().items(Joi.object()).optional(),
  maintenanceSchedule: Joi.array().items(Joi.object()).optional(),
  parts: Joi.array().items(Joi.object()).optional(),
  documents: Joi.array().items(Joi.object()).optional(),
  performanceMetrics: Joi.object().optional(),
  warrantyStatus: Joi.string().optional(),
  maintenanceStatus: Joi.string().optional(),
  lastMaintenance: Joi.date().optional(),
  lastMaintenanceDate: Joi.date().optional(),
  maintenanceFrequency: Joi.string().optional(),
  maintenanceProvider: Joi.string().optional(),
  nextService: Joi.date().optional(),
  owner: Joi.string().optional(),
  department: Joi.string().optional(),
  tags: Joi.array().items(Joi.string()).optional(),
  customFields: Joi.object().optional()
});

const updateAssetSchema = Joi.object({
  name: Joi.string().optional().min(3).max(100),
  assetNumber: Joi.string().optional(),
  assetTag: Joi.string().optional(),
  code: Joi.string().optional(),
  shortDescription: Joi.string().optional().max(500),
  description: Joi.string().optional().max(500),
  category: Joi.string().optional(),
  type: Joi.string().optional(),
  location: Joi.string().optional(),
  propertyLocation: Joi.string().optional(),
  buildingLocation: Joi.string().optional(),
  building: Joi.string().optional(),
  floor: Joi.string().optional(),
  room: Joi.string().optional(),
  serviceArea: Joi.string().optional(),
  status: Joi.string().optional().valid('active', 'inactive', 'maintenance', 'retired'),
  condition: Joi.string().optional().valid('excellent', 'good', 'fair', 'poor'),
  images: Joi.array().items(Joi.string()).optional(),
  imageUrl: Joi.string().optional(),
  imageUrls: Joi.array().items(Joi.string()).optional(),
  serialNumber: Joi.string().optional(),
  serial: Joi.string().optional(),
  manufacturer: Joi.string().optional(),
  modelNumber: Joi.string().optional(),
  model: Joi.string().optional(),
  installationDate: Joi.date().optional(),
  installDate: Joi.date().optional(),
  specs: Joi.object().optional(),
  purchasePrice: Joi.number().optional().min(0),
  purchaseDate: Joi.date().optional(),
  depreciationRate: Joi.number().optional().min(0),
  warranty: Joi.object({
    expires: Joi.date().optional(),
    provider: Joi.string().optional(),
    purchaseDate: Joi.date().optional()
  }).optional(),
  nextMaintenanceDate: Joi.date().optional(),
  nextService: Joi.date().optional(),
  lastMaintenance: Joi.date().optional(),
  lastMaintenanceDate: Joi.date().optional(),
  maintenanceFrequency: Joi.string().optional(),
  maintenanceProvider: Joi.string().optional(),
  notes: Joi.string().optional(),
  maintenanceHistory: Joi.array().items(Joi.object()).optional(),
  maintenanceSchedule: Joi.array().items(Joi.object()).optional(),
  parts: Joi.array().items(Joi.object()).optional(),
  documents: Joi.array().items(Joi.object()).optional(),
  performanceMetrics: Joi.object().optional(),
  warrantyStatus: Joi.string().optional(),
  maintenanceStatus: Joi.string().optional(),
  owner: Joi.string().optional(),
  tags: Joi.array().items(Joi.string()).optional()
}).min(1);

module.exports = {
  createAssetSchema,
  updateAssetSchema,
  bulkAssetStatusSchema: Joi.object({
    ids: Joi.array().items(Joi.string()).min(1).required(),
    status: Joi.string().required().valid('active', 'inactive', 'maintenance', 'retired')
  })
};
